# Site settings
title: "Danielle Lieber Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Danielle Lieber"
resume_title:                   ""
resume_contact_email:           "lieberkd@gmail.com"
resume_contact_telephone:       "305-335-3327"
resume_contact_address:         "605 Tasman Dr. Apt. 1103 Sunnyvale, CA 94089"
resume_header_contact_info: "605 Tasman Dr. Apt. 1103 Sunnyvale, CA | 305-335-3327 | lieberkd@gmail.com"
resume_header_intro: "<p>Analytical, data driven engineer with diverse skill set in research and development. Experienced in programming, product development, laboratory testing, and data analysis. Interested in solving challenging problems in biotech, big data, and next generation medical devices. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_publications:    true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/danusk"
  resume_facebook_url:          "https://www.facebook.com/danielle.lieber.3"
  resume_linkedin_url:          "https://www.linkedin.com/in/danielle-lieber-772300119"
#  resume_website_url:          
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
